# Generated by Django 6.0.6 on 2026-07-16 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenalTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(help_text='Ej: XAUUSD, US30', max_length=20)),
                ('tipo', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=10)),
                ('precio_entrada', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sl', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Stop Loss')),
                ('tp', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Take Profit')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRUEBA', '15 Días Gratis'), ('PENDIENTE', 'Esperando Comprobante QR'), ('ACTIVO', 'Suscripción Pagada'), ('VENCIDO', 'Acceso Bloqueado')], default='PRUEBA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_acceso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
