# Generated by Django 6.0.6 on 2026-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_vip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senaltrading',
            name='beneficio_pips',
            field=models.IntegerField(blank=True, help_text='Pips de TP (Ej: 150)', null=True),
        ),
        migrations.AddField(
            model_name='senaltrading',
            name='riesgo_pips',
            field=models.IntegerField(blank=True, help_text='Pips de SL (Ej: 50)', null=True),
        ),
    ]
