# Generated by Django 6.0.6 on 2026-07-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_vip', '0002_senaltrading_beneficio_pips_senaltrading_riesgo_pips'),
    ]

    operations = [
        migrations.AddField(
            model_name='senaltrading',
            name='resultado',
            field=models.CharField(choices=[('EN_CURSO', 'En Curso ⏳'), ('GANANCIA', 'Ganancia (TP) ✅'), ('PERDIDA', 'Pérdida (SL) ❌'), ('BE', 'Break Even 🛡️')], default='EN_CURSO', max_length=20),
        ),
    ]
