# Generated by Django 6.0.6 on 2026-07-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_vip', '0003_senaltrading_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='senaltrading',
            name='lotaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 0.01', max_digits=10, null=True),
        ),
    ]
